# Generated by Django 5.0.4 on 2024-04-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='university_info1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('established_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='university_info2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_majors', models.IntegerField()),
                ('number_students', models.IntegerField()),
                ('number_teachers', models.IntegerField()),
            ],
        ),
    ]
